services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@db/${AIRFLOW_DB_NAME}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./app:/opt/airflow/app
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@db/${AIRFLOW_DB_NAME}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./app:/opt/airflow/app
    command: scheduler

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sh:/docker-entrypoint-initdb.d/init.sh

  dbt:
    build:
      context: .
      dockerfile: Dockerfile.dbt
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/app/dbt
      - ./dbt_profile:/root/.dbt
    profiles: ["tools"]
    depends_on:
      - db

volumes:
  postgres_data:
