FROM python:3.12-slim
RUN pip install --no-cache-dir dbt-postgres==1.8.* dbt-core==1.8.*
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
WORKDIR /usr/app/dbt
ENTRYPOINT ["dbt"]
